version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: dev_talk_database
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./migrations/models.sql:/docker-entrypoint-initdb.d/models.sql
    networks:
      - app_network

  app:
    build:
      context: .
    container_name: dt-articles
    environment:
      MYSQL_HOST: dev_talk_database
      MYSQL_PORT: 3306
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    depends_on:
      - mysql
    networks:
      - app_network
    ports:
      - "8000:8000"
    command: >
      sh -c "/wait-for-it.sh dev_talk_database:3306 -- uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  mysql_data:
    driver: local

networks:
  app_network:
    driver: bridge
