name: Publish

on:
  workflow_run:
    workflows:
      - Tests
    types:
      - completed
  workflow_dispatch:

jobs:
  docker-publish:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    if: >-
      github.event.workflow_run.conclusion == "success" &&
      github.event.workflow_run.name == "Tests" &&
      github.event.workflow_run.head_branch == "main"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set repository name
        id: repo
        run: echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO_NAME }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
