name: Security Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  security-check:
    name: Security check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install security tools
        run: pip install bandit safety

      - name: Run Bandit scan
        run: |
          bandit -r . --severity-level high --confidence-level high || \
          echo "Bandit found issues (non-blocking)" >&2
          bandit -r . -f html -o security-report.html || true

      - name: Run Safety scan
        run: |
          safety scan --full-report --exit-zero || \
          echo "Safety found vulnerabilities (non-blocking)" >&2

      - name: Upload security report
        uses: actions/upload-artifact@v4
        with:
          name: security-report
          path: security-report.html
